## 1.4.3 (2019-02-26)

#### :bug: Bug Fix
  * [#126](https://github.com/Kentico/kentico-cloud-js/pull/126) Stores current retry attempt to ensure correct timeout is used for retrying additional requests ([@Enngage](https://github.com/Enngage))
  
## 1.4.2 (2019-02-26)

#### :bug: Bug Fix
  * [#123](https://github.com/Kentico/kentico-cloud-js/pull/123) Fix response mapping if request is successful for the first time ([@Enngage](https://github.com/Enngage))
  
## 1.4.1 (2019-02-26)

#### :bug: Bug Fix
  * [#122](https://github.com/Kentico/kentico-cloud-js/pull/122) Fixes mapping of Promise response ([@Enngage](https://github.com/Enngage))
  
## 1.4.0 (2019-02-26)

#### :rocket: Enhancement
  * [#121](https://github.com/Kentico/kentico-cloud-js/pull/121) Adds support for retrying Promises ([@Enngage](https://github.com/Enngage))
  * [#112](https://github.com/Kentico/kentico-cloud-js/pull/112) Link test http service mention to the docs ([@Simply007](https://github.com/Simply007))
